[theme]
backgroundColor = "#F7F3EE"
textColor = "#4A4A4A"
headingFont = "Montserrat"
font = "Roboto"
greenColor = "#0B6E4F"
blueColor = "#1B365D"
yellowColor = "#F6C84C"
orangeColor = "#F95A2B"
primaryColor = "#0B6E4F"
