MAPPING_TYPE_GENERATEUR = {
    "systÃ\x83Â¨me collectif par dÃ\x83Â©faut en abscence d'information : chaudiÃ\x83Â¨re fioul pÃ\x83Â©nalisante": "Système de production d'ecs non électrique",
    "RÃ\x83Â©seau de chaleur isolÃ\x83Â©": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois granulÃ\x83Â©s 2004-2012": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che 1995-2003": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz basse tempÃ\x83Â©rature 2001-2015": "Système de production d'ecs non électrique",
    "poÃ\x83Âªle Ã\x83Â\xa0 bois bouilleur bÃ\x83Â»che installÃ\x83Â© Ã\x83Â\xa0 partir de 2012": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul classique avant 1970": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz classique avant 1981": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz Ã\x83Â\xa0 condensation 2001-2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz standard 2001-2015": "Système de production d'ecs non électrique",
    "Ballon Ã\x83Â©lectrique Ã\x83Â\xa0 accumulation vertical Autres ou inconnue": "Ballon électrique",
    "ChaudiÃ\x83Â¨re gaz classique 1986-1990": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz standard aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul standard 1991-2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul Ã\x83Â\xa0 condensation 1996-2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul classique 1970-1975": "Système de production d'ecs non électrique",
    "Ballon Ã\x83Â©lectrique Ã\x83Â\xa0 accumulation vertical CatÃ\x83Â©gorie B ou 2 Ã\x83Â©toiles": "Ballon électrique",
    "Ballon Ã\x83Â©lectrique Ã\x83Â\xa0 accumulation vertical CatÃ\x83Â©gorie C ou 3 Ã\x83Â©toiles": "Ballon électrique",
    "ChaudiÃ\x83Â¨re gaz Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "Chaudière gaz basse température 2001-2015": "Système de production d'ecs non électrique",
    "PAC double service 2010-2014": "Pompe à chaleur",
    "autre systÃ\x83Â¨me Ã\x83Â\xa0 combustion bois": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul basse tempÃ\x83Â©rature 1991-2015": "Système de production d'ecs non électrique",
    "CET sur air ambiant (sur local non chauffÃ\x83Â©) aprÃ\x83Â¨s 2014": "Chauffe-eau thermodynamique",
    "Ballon Ã\x83Â©lectrique Ã\x83Â\xa0 accumulation horizontal": "Ballon électrique",
    "Chauffe-eau gaz Ã\x83Â\xa0 production instantanÃ\x83Â©e avant 1980": "Système de production d'ecs non électrique",
    "chauffe-eau Ã\x83Â©lectrique instantanÃ\x83Â©": "Chauffe-eau électrique",
    "CET sur air extÃ\x83Â©rieur aprÃ\x83Â¨s 2014": "Chauffe-eau thermodynamique",
    "ChaudiÃ\x83Â¨re fioul classique 1981-1990": "Système de production d'ecs non électrique",
    "PAC double service aprÃ\x83Â¨s 2014": "Pompe à chaleur",
    "ChaudiÃ\x83Â¨re fioul Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "Chauffe-eau gpl/propane/butane Ã\x83Â\xa0 production instantanÃ\x83Â©e aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane Ã\x83Â\xa0 condensation 2001-2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re Ã\x83Â©lectrique": "Chaudière électrique",
    "Chauffe-eau gpl/propane/butane Ã\x83Â\xa0 production instantanÃ\x83Â©e avant 1980": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul classique 1976-1980": "Système de production d'ecs non électrique",
    "Chauffe-eau gpl/propane/butane Ã\x83Â\xa0 production instantanÃ\x83Â©e 1990-2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz standard 1991-2000": "Système de production d'ecs non électrique",
    "Chauffe-eau gaz Ã\x83Â\xa0 production instantanÃ\x83Â©e 1990-2000": "Système de production d'ecs non électrique",
    "CET sur air ambiant (sur local non chauffÃ\x83Â©) avant 2010": "Chauffe-eau thermodynamique",
    "CET sur air extrait aprÃ\x83Â¨s 2014": "Chauffe-eau thermodynamique",
    "ChaudiÃ\x83Â¨re gaz basse tempÃ\x83Â©rature aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "autre systÃ\x83Â¨me Ã\x83Â\xa0 combustion gaz": "Système de production d'ecs non électrique",
    "Chauffe-eau gaz Ã\x83Â\xa0 production instantanÃ\x83Â©e aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "Chauffe-eau gaz Ã\x83Â\xa0 production instantanÃ\x83Â©e 2001-2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz basse tempÃ\x83Â©rature 1991-2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois plaquette 2013-2017": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz classique 1981-1985": "Système de production d'ecs non électrique",
    "RÃ\x83Â©seau de chaleur non isolÃ\x83Â©": "Système de production d'ecs non électrique",
    "Chauffe-eau gaz Ã\x83Â\xa0 production instantanÃ\x83Â©e 1981-1989": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz Ã\x83Â\xa0 condensation 1981-1985": "Système de production d'ecs non électrique",
    "CET sur air ambiant (sur local non chauffÃ\x83Â©) 2010-2014": "Chauffe-eau thermodynamique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re gaz Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2015": "Pompe à chaleur",
    "ChaudiÃ\x83Â¨re(s) bois multi bÃ\x83Â¢timent modÃ\x83Â©lisÃ\x83Â©e comme un rÃ\x83Â©seau de chaleur": "Système de production d'ecs non électrique",
    "PAC double service avant 2010": "Pompe à chaleur",
    "ChaudiÃ\x83Â¨re fioul standard aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gaz Ã\x83Â\xa0 condensation 1986-2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane standard 2001-2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che 2013-2017": "Système de production d'ecs non électrique",
    "CET sur air extrait 2010-2014": "Chauffe-eau thermodynamique",
    "ChaudiÃ\x83Â¨re bois granulÃ\x83Â©s 2013-2019": "Système de production d'ecs non électrique",
    "Accumulateur gaz Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois granulÃ\x83Â©s aprÃ\x83Â¨s 2019": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che 1978-1994": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re(s) gaz multi bÃ\x83Â¢timent modÃ\x83Â©lisÃ\x83Â©e comme un rÃ\x83Â©seau de chaleur": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che avant 1978": "Système de production d'ecs non électrique",
    "CET sur air extrait avant 2010": "Chauffe-eau thermodynamique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane basse tempÃ\x83Â©rature 2001-2015": "Système de production d'ecs non électrique",
    "Accumulateur gaz classique avant 1990": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane standard 1991-2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "Accumulateur gaz classique aprÃ\x83Â¨s 2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che 2004-2012": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re fioul basse tempÃ\x83Â©rature aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "rÃ\x83Â©seau de chaleur non rÃ\x83Â©pertoriÃ\x83Â© ou inconnu": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane standard aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois plaquette 2018-2019": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois plaquette 1995-2003": "Système de production d'ecs non électrique",
    "CET sur air extÃ\x83Â©rieur avant 2010": "Chauffe-eau thermodynamique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re fioul Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2015": "Pompe à chaleur",
    "ChaudiÃ\x83Â¨re(s) fioul multi bÃ\x83Â¢timent modÃ\x83Â©lisÃ\x83Â©e comme un rÃ\x83Â©seau de chaleur": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane classique avant 1981": "Système de production d'ecs non électrique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re bois bÃ\x83Â»che 2013-2017": "Pompe à chaleur",
    "ChaudiÃ\x83Â¨re bois plaquette aprÃ\x83Â¨s 2019": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane basse tempÃ\x83Â©rature 1991-2000": "Système de production d'ecs non électrique",
    "autre systÃ\x83Â¨me Ã\x83Â\xa0 combustion autres energies fossiles (charbon,pÃ\x83Â©trole etcÃ¢Â\x80Â¦)": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane basse tempÃ\x83Â©rature aprÃ\x83Â¨s 2015": "Système de production d'ecs non électrique",
    "Pompe(s) Ã\x83Â\xa0 chaleur multi bÃ\x83Â¢timent modÃ\x83Â©lisÃ\x83Â©e comme un rÃ\x83Â©seau de chaleur": "Pompe à chaleur",
    "Accumulateur gaz classique 1990-2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane Ã\x83Â\xa0 condensation 1986-2000": "Système de production d'ecs non électrique",
    "Chauffe-eau gpl/propane/butane Ã\x83Â\xa0 production instantanÃ\x83Â©e 2001-2015": "Système de production d'ecs non électrique",
    "Accumulateur gpl/propane/butane classique 1990-2000": "Système de production d'ecs non électrique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re gaz Ã\x83Â\xa0 condensation 2001-2015": "Pompe à chaleur",
    "autre systÃ\x83Â¨me thermodynamique Ã\x83Â©lectrique": "Système de production d'ecs non électrique",
    "Chauffe-eau gpl/propane/butane Ã\x83Â\xa0 production instantanÃ\x83Â©e 1981-1989": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane classique 1986-1990": "Système de production d'ecs non électrique",
    "autre systÃ\x83Â¨me Ã\x83Â\xa0 combustion fioul": "Système de production d'ecs non électrique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re gpl/propane/butane Ã\x83Â\xa0 condensation 2001-2015": "Pompe à chaleur",
    "Accumulateur gpl/propane/butane Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re charbon avant 1978": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re gpl/propane/butane classique 1981-1985": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois plaquette 2004-2012": "Système de production d'ecs non électrique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re fioul Ã\x83Â\xa0 condensation 1996-2015": "Pompe à chaleur",
    "Accumulateur gaz Ã\x83Â\xa0 condensation 1996-2000": "Système de production d'ecs non électrique",
    "Accumulateur gpl/propane/butane classique avant 1990": "Système de production d'ecs non électrique",
    "Accumulateur gpl/propane/butane classique aprÃ\x83Â¨s 2000": "Système de production d'ecs non électrique",
    "poÃ\x83Âªle Ã\x83Â\xa0 bois bouilleur granulÃ\x83Â©s installÃ\x83Â© Ã\x83Â\xa0 partir de 2012": "Système de production d'ecs non électrique",
    "poÃ\x83Âªle Ã\x83Â\xa0 bois bouilleur bÃ\x83Â»che installÃ\x83Â© avant 2012": "Système de production d'ecs non électrique",
    "pompe Ã\x83Â\xa0 chaleur hybride : partie chaudiÃ\x83Â¨re ChaudiÃ\x83Â¨re gpl/propane/butane Ã\x83Â\xa0 condensation aprÃ\x83Â¨s 2015": "Pompe à chaleur",
    "ChaudiÃ\x83Â¨re gpl/propane/butane Ã\x83Â\xa0 condensation 1981-1985": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che aprÃ\x83Â¨s 2019": "Système de production d'ecs non électrique",
    "poÃ\x83Âªle Ã\x83Â\xa0 bois bouilleur granulÃ\x83Â©s installÃ\x83Â© avant 2012": "Système de production d'ecs non électrique",
    "Accumulateur gpl/propane/butane Ã\x83Â\xa0 condensation 1996-2000": "Système de production d'ecs non électrique",
    "ChaudiÃ\x83Â¨re bois bÃ\x83Â»che 2018-2019": "Système de production d'ecs non électrique",
    "CET sur air extÃÂ©rieur 2010-2014": "Chauffe-eau thermodynamique",
}

# Valeur par défaut si aucune correspondance n’est trouvée
DEFAULT_GENERATEUR = "Système de production d'ecs non électrique"
