-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DPE_030326"
(
    numero_dpe character varying COLLATE pg_catalog."default",
    date_etablissement_dpe character varying COLLATE pg_catalog."default",
    etiquette_dpe character varying COLLATE pg_catalog."default",
    zone_climatique character varying COLLATE pg_catalog."default",
    code_departement_ban integer,
    code_postal_ban integer,
    code_insee_ban integer,
    nom_commune_ban character varying COLLATE pg_catalog."default",
    classe_altitude character varying COLLATE pg_catalog."default",
    type_batiment character varying COLLATE pg_catalog."default",
    annee_construction integer,
    periode_construction character varying COLLATE pg_catalog."default",
    position_logement_dans_immeuble character varying COLLATE pg_catalog."default",
    surface_habitable_logement character varying COLLATE pg_catalog."default",
    hauteur_sous_plafond character varying COLLATE pg_catalog."default",
    surface_climatisee character varying COLLATE pg_catalog."default",
    surface_chauffee_installation_chauffage_n1 character varying COLLATE pg_catalog."default",
    surface_habitable_desservie_par_installation_ecs_n1 character varying COLLATE pg_catalog."default",
    numero_etage_appartement integer,
    logement_traversant integer,
    type_energie_n1 character varying COLLATE pg_catalog."default",
    type_energie_principale_chauffage character varying COLLATE pg_catalog."default",
    type_energie_climatisation character varying COLLATE pg_catalog."default",
    type_generateur_froid character varying COLLATE pg_catalog."default",
    type_emetteur_installation_chauffage_n1 character varying COLLATE pg_catalog."default",
    type_generateur_n1_ecs_n1 character varying COLLATE pg_catalog."default",
    type_energie_principale_ecs character varying COLLATE pg_catalog."default",
    configuration_installation_chauffage_n1 character varying COLLATE pg_catalog."default",
    configuration_installation_ecs_n1 character varying COLLATE pg_catalog."default",
    conso_5_usages_par_m2_ep character varying COLLATE pg_catalog."default",
    conso_ecs_ep character varying COLLATE pg_catalog."default",
    conso_chauffage_ep character varying COLLATE pg_catalog."default",
    conso_eclairage_ep character varying COLLATE pg_catalog."default",
    conso_refroidissement_ep character varying COLLATE pg_catalog."default",
    conso_refroidissement_annuel character varying COLLATE pg_catalog."default",
    conso_5_usages_ep character varying COLLATE pg_catalog."default",
    conso_auxiliaires_ep character varying COLLATE pg_catalog."default",
    cout_eclairage character varying COLLATE pg_catalog."default",
    cout_chauffage character varying COLLATE pg_catalog."default",
    cout_total_5_usages character varying COLLATE pg_catalog."default",
    cout_auxiliaires character varying COLLATE pg_catalog."default",
    cout_ecs character varying COLLATE pg_catalog."default",
    cout_refroidissement character varying COLLATE pg_catalog."default",
    classe_inertie_batiment character varying COLLATE pg_catalog."default",
    indicateur_confort_ete character varying COLLATE pg_catalog."default",
    apport_solaire_saison_chauffe character varying COLLATE pg_catalog."default",
    ventilation_posterieure_2012 integer,
    presence_brasseur_air integer,
    production_electricite_pv_kwhep_par_an character varying COLLATE pg_catalog."default",
    isolation_toiture integer,
    qualite_isolation_enveloppe character varying COLLATE pg_catalog."default",
    deperditions_enveloppe character varying COLLATE pg_catalog."default",
    protection_solaire_exterieure integer,
    apport_interne_saison_froide character varying COLLATE pg_catalog."default",
    apport_interne_saison_chauffe character varying COLLATE pg_catalog."default",
    apport_solaire_saison_froide character varying COLLATE pg_catalog."default",
    ubat_w_par_m2_k character varying COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public."DPE_030326"
    ENABLE ROW LEVEL SECURITY;
END;