-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Conso_annuelle_dpt"
(
    "Key" character varying COLLATE pg_catalog."default",
    "Annee" integer,
    "Code_region" integer,
    "Nom_region" character varying COLLATE pg_catalog."default",
    "Code_dpt" character varying COLLATE pg_catalog."default",
    "Nom_dpt" character varying COLLATE pg_catalog."default",
    "Nb_operateurs" integer,
    "Code_gd_secteur" character varying COLLATE pg_catalog."default",
    "Code_categorie" character varying COLLATE pg_catalog."default",
    "Filiere" character varying COLLATE pg_catalog."default",
    "Nb_mailles_secretisees" integer,
    "Nb_sites" integer,
    "Conso_totale_MWH" double precision,
    "Conso_moy_MWH" double precision,
    "Conso_totale_usages_thermosensibles_MWH" double precision,
    "Conso_moy_usages_thermosensibles_MWH" double precision,
    "Conso_totale_usages_non_thermosensibles_MWH" double precision,
    "Conso_moy_usages_non_thermosensibles_MWH" double precision,
    "Thermosensibilite_totale_KWH_DJU" double precision,
    "Thermosensibilite_moy_KWH_DJU" double precision,
    "Part_thermosensible_pourcentage" double precision,
    "Conso_totale_corrigee_alea_climatique_usages_thermosensibles" double precision,
    "Conso_moy_corrigee_alea_climatique_usages_thermosensibles" double precision,
    "DJU_a_TR" double precision,
    "DJU_a_TN" double precision
);

ALTER TABLE IF EXISTS public."Conso_annuelle_dpt"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Conso_quot_nationale"
(
    "Date_heure" character varying COLLATE pg_catalog."default",
    "Consommation_brute_elec_MW_RTE" integer,
    "Statut_RTE" character varying COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public."Conso_quot_nationale"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Conso_quot_regionale"
(
    "Date_heure" character varying COLLATE pg_catalog."default",
    "Date" character varying COLLATE pg_catalog."default",
    "Heure" character varying COLLATE pg_catalog."default",
    "Nature" character varying COLLATE pg_catalog."default",
    "Conso_MWH" integer,
    "Eolien" integer,
    "Solaire" integer,
    "Hydraulique" integer,
    "Pompage" integer,
    "Region" character varying COLLATE pg_catalog."default",
    "Thermique" integer,
    "Nucleaire" integer,
    "Bioenergies" integer,
    "TCO_thermique_pourcentage" double precision,
    "TCO_nucleaire_pourcentage" integer,
    "TCO_eolien_pourcentage" double precision,
    "TCO_solaire_pourcentage" double precision,
    "TCO_hydraulique_pourcentage" double precision,
    "TCO_bioenergies_pourcentage" double precision,
    "TCO_exterieur_pourcentage" double precision
);

ALTER TABLE IF EXISTS public."Conso_quot_regionale"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Meteo"
(
    "ID" character varying COLLATE pg_catalog."default",
    "NUM_POSTE" integer,
    "NOM_POSTATION" character varying COLLATE pg_catalog."default",
    "CODE_DEPARTEMENT" integer,
    "LATITUDE" double precision,
    "LONGITUDE" double precision,
    "ALTITUDE" integer,
    "DATE_RELEVE" character varying COLLATE pg_catalog."default",
    "PRECIPITATION_QUANTITE_24H" double precision,
    "TEMP_MIN_SOUS_ABRI" double precision,
    "HEURE_TEMP_MIN_SA" character varying COLLATE pg_catalog."default",
    "TEMP_MAX_SA" double precision,
    "HEURE_TEMP_MAX_SA" character varying COLLATE pg_catalog."default",
    "MOYENNE_TEMP_HORAIRES_SA_PONDEREE" double precision,
    "MOYENNE_TEMP" double precision,
    "AMPLITUDE_THERMIQUE_QUOTIDENNE" double precision,
    "TEMP_MIN_10SOL" double precision,
    "TEMP_MIN_50CM" double precision,
    "DUREE_GEL_SOUSABRI" integer,
    "MOYENNE_FORCE_VENT_10M" double precision,
    "MAX_FORCE_VENT_10M" double precision,
    "MAX_FORCE_VENT_10M_INST" double precision,
    "MAX_FORCE_VENT_MOY_3S" double precision,
    "HEURE_MAX_FORCE_VENT_10M_" character varying COLLATE pg_catalog."default",
    "DUREE_PRECIPITATIONS" integer,
    "HEURE_PIC_FORCE_MAX_VENT" character varying COLLATE pg_catalog."default",
    "DIRECTION_FORCE_VENT" integer,
    "RAYONNEMENT_DIFFUS" character varying COLLATE pg_catalog."default",
    "SOMME_RAYONNEMENT_INFRAROUGE" character varying COLLATE pg_catalog."default",
    "CUMUL_RAYONNEMENT_ULTRAVIOLET" character varying COLLATE pg_catalog."default",
    "MAX_INDICESUV_HORAIRES" character varying COLLATE pg_catalog."default",
    "MIN_HUMIDITES_RELATIVES_MIN_HORAIRES" integer,
    "HEURE_MIN_HUMIDITES_RELATIVES" character varying COLLATE pg_catalog."default",
    "MAX_HUMIDITES_RELATIVES_MAX_HORAIRES" integer,
    "HEURE_MAX_HUMIDITES_RELATIVES" character varying COLLATE pg_catalog."default",
    "MOYENNE_HUMIDITES_RELATIVES_HORAIRES" integer,
    "DUREE_HUMIDITE_40" integer,
    "DUREE_HUMIDITE_80" integer,
    "TENSION_VAPEUR_MOYENNE" double precision,
    "ETP_GRILLE" double precision,
    "ECOULEMENTM" character varying COLLATE pg_catalog."default",
    "EPAISSEUR_NEIGE" integer,
    "EPAISSEUR_NEIGE_SOL_6H" integer,
    "OCCURENCE_NEIGE" integer,
    "OCCURENCE_BROUILLARD" integer,
    "OCCURENCE_VERGLAS" integer,
    "OCCURENCE_GELEE" integer,
    "OCCURENCE_FUMEE" integer,
    "OCCURENCE_BRUME" integer,
    "TEMPERATURE_MER_MIN" character varying COLLATE pg_catalog."default",
    "TEMPERATURE_MER_MAX" character varying COLLATE pg_catalog."default",
    "MOYENNE_FORCE_VENT_2M" character varying COLLATE pg_catalog."default",
    "FORCE_MAX_VENT_INSTANTANEE_2M" character varying COLLATE pg_catalog."default",
    "DIRECTION_MAX_FORCE_VENT_2M" character varying COLLATE pg_catalog."default",
    "HEURE_MAX_FORCE_VENT_2M" character varying COLLATE pg_catalog."default",
    "DIRECTION_MAX_FORCE_VENT_MOY_3S" integer,
    "OCCURENCE_ORAGE" integer,
    "OCCURENCE_GRESIL" character varying COLLATE pg_catalog."default",
    "OCCURENCE_GRELE" integer,
    "OCCURENCE_ROSEE" character varying COLLATE pg_catalog."default",
    "OCCURENCE_SOL_COUVERT_NEIGE" character varying COLLATE pg_catalog."default",
    "OCCURENCE_ECLAIR" character varying COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public."Meteo"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Soleil"
(
    "Date (UTC)" date,
    "Instant du lever (heure)" time without time zone,
    "Instant du coucher (heure)" time without time zone,
    "Date&Time Difference" bigint
);

ALTER TABLE IF EXISTS public."Soleil"
    ENABLE ROW LEVEL SECURITY;
END;